### ISSUE TITLE
Can't push branch if remote is missing

### ISSUE THREAD

**Issue by ameijboom** [dmeijboom/src#3]
We can currently not push any branches which do not exist on remote yet.
This makes it so that we can't push changes to a new branch without creating the remote branch first.

```sh
Pushing to: ⬡ origin /  feature/dev-517-deploy-atlantis-to-brainhive-prod
⚠️ update rejected (outdated); code=User (-7)
```

**Comment by dmeijboom** [comment]
Fixed!
