### ISSUE TITLE
[bug] Can't checkout branch or add files when not in root project folder.

### ISSUE THREAD

**Issue by ameijboom** [dmeijboom/src#5]
When attempting to either checkout a branch (such as `src main`) while in a different folder within the project, we get the following error:

```
folder/in/project
➜ src main
⚠️ failed to resolve path '.': No such file or directory; class=Os (2); code=NotFound (-3)
```

The same happens when attempting to `src add`.
For added context, I was in a nested folder 5 layers deep (/project/1/2/3/4/5)

**Comment by dmeijboom** [comment]
Human error: folder does not exists ..
